# Generated by Django 5.2.7 on 2026-05-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizers', to='directory.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='directory.organizer')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='directory_l_name_c5c6ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'organizer'), name='unique_location_per_organizer')],
            },
        ),
    ]
