# Generated by Django 5.2.7 on 2026-05-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_location_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='aliases',
            field=models.TextField(blank=True, help_text='Optional comma-separated local names or spellings, e.g. Malayalam names.'),
        ),
    ]
